### ISSUE TITLE
Develop a v0 deliverables list

### ISSUE THREAD

**Issue by brandonschabell** [PantryChef/PantryChef#1]
We need to come up with a list of requirements for a "Version 0" release.
This release does not need to be ship-able, but should contain enough functionality to serve as a base app from which divergent development can take place (i.e. dev1 can work on issue A while dev2 works on issue B.)

Let's discuss requirements in the comments below, and after an agreement has been reached, we can convert these requirements into issues and add them to the backlog.

**Comment by brandonschabell** [comment]
For our first version, I don't think any sort of signon/account information will be necessary. We can certainly add that in the future, but for now let's focus on creating a function landing page. This could contain a couple buttons such as, "Scan Item" and "Find Recipes". Can anyone think of anything else that would be necessary for a version 0?

**Comment by brandonschabell** [comment]
We may also want to consider adopting an automated testing framework. I'm not sold on CI builds, especially for mobile apps, but I'm open to hearing others' opinions on the matter.

**Comment by KJ-Caramel** [comment]
The UI testing framework that is mentioned in the official google docs is Espresso...might as well go with that one

**Comment by brandonschabell** [comment]
@KJ-Caramel I'd be okay with Espresso (and Jenkins.)

**Comment by brandonschabell** [comment]
Scratch that- Travis over Jenkins, since we don't have a server.

**Comment by brandonschabell** [comment]
@KJ-Caramel I got Travis working, so we're now set up for continuous integration.

**Comment by KJ-Caramel** [comment]
@brandonschabell  okay we'll have to sit down and go over like all the tools before doing commits and all. Not too familiar with Travis CI . Are there any other tools that we are missing at the moment? JUnit is integrated so don't have to worry about unit tests thankfully. And we agree to use Espresso as the front-end testing framework right?

**Comment by KJ-Caramel** [comment]
thoughts about V0 of PantryChef- 
welcome screen with two buttons: Scan, MyPantry
Scan: scanning a label but the button wouldn't do anything (for now)
MyPantry: button that leads to a list of items that you have in your pantry, that you can also add to, almost like a checklist/todo-list

**Comment by brandonschabell** [comment]
@KJ-Caramel I don't really know much about Espresso, but I'm fine with going that route until I hear an argument not to. 

As for Travis, it basically runs a script behind the scenes when you make a commit. If you look at the commit list, you'll notice a green checkmark, a red x, or a yellow circle. Green checkmark means everything built and tests ran successfully (once we add tests). Red means it didn't, and yellow is still running.

Those are the only dev tools I can think of that we really need right now. Of course we'll need things like a local storage option and other pieces of backend infrastructure, but we can cross that bridge when we get there.

I agree with the welcome screen containing "Scan" and "MyPantry", probably a "Find Recipes" button as well, although I could be convinced to put that in the "MyPantry section if that wouldn't make it too busy. Let's at least get some blank pages set up for those 2 (or 3) buttons in order to prevent future merge conflicts on the main page.

I think that along with issue #3 and creating a very basic roadmap should suffice for a jumping off point a.k.a. version 0.

**Comment by brandonschabell** [comment]
@avaidyam I know you said you were considering adding an issue- is there anything you think we missed for a barebones setup?

**Comment by brandonschabell** [comment]
I created a [Roadmap](https://github.com/PantryChef/PantryChef/wiki/Roadmap). Unless anyone has something else to add, I will close this issue.

**Comment by brandonschabell** [comment]
Closing this issue. Additional comments can be made in the discord chat.
