### ISSUE TITLE
Create local storage

### ISSUE THREAD

**Issue by brandonschabell** [PantryChef/PantryChef#11]
Look into a SQL database that can be used to store data locally in the future.

**Comment by brandonschabell** [comment]
I'm going to take a crack at getting SQLiteOpenHelper set up.

**Comment by KJ-Caramel** [comment]
android comes with a sql lite database that is stored along with the app on the phone, that should suffice but mayybeeeee doing firebase could be good?

**Comment by brandonschabell** [comment]
@KJ-Caramel  Firebase may be something worth looking into once we get to cloud based features, but for local storage, it doesn't offer any solutions. SQLiteDatabase seems to be the go-to.

**Comment by brandonschabell** [comment]
A pull request has been issued. I'll close it out once that gets approved.
@KJ-Caramel

**Comment by brandonschabell** [comment]
This has been merged into dev.
