### ISSUE TITLE
Create a landing page

### ISSUE THREAD

**Issue by brandonschabell** [PantryChef/PantryChef#6]
The landing page should have buttons that direct to:

- My Pantry
- My Recipes

Each of these pages can be blank for now, but we should still drop them to the page to prevent future merge conflicts.

**Comment by KJ-Caramel** [comment]
question is, do we just got with stock UI from the start and later add material design? Material design is sexy

**Comment by brandonschabell** [comment]
@KJ-Caramel I was thinking that this would be a super basic page and issue #12 would pretty it up.

**Comment by KJ-Caramel** [comment]
@brandonschabell  assign this to **me**, I'll get it started up this weekend

**Comment by brandonschabell** [comment]
@KJ-Caramel Do it quick! Otherwise, I may beat you to it. ;-)

**Comment by KJ-Caramel** [comment]
@brandonschabell  lol okay. I'll work on it tomorrow...still getting this pc set up

**Comment by brandonschabell** [comment]
@KJ-Caramel Haha sounds good.

**Comment by KJ-Caramel** [comment]
@brandonschabell  code and all is done & completed for this issue....to do a pull request...thats another story lol

**Comment by KJ-Caramel** [comment]
@brandonschabell  i'm trying to push my local repo to be tracked on here to do a pull request but this is what i'm getting: 

Karan@DESKTOP-8Q98IHS MINGW32 ~/Documents/Programming/PantryChef (ISSUE-6-Create-Landing-Page)
$ git push -u origin ISSUE-6-Create-Landing-Page
remote: Permission to PantryChef/PantryChef.git denied to KJ-Caramel.
fatal: unable to access 'https://github.com/PantryChef/PantryChef.git/': The requested URL returned error: 403

**Comment by brandonschabell** [comment]
@KJ-Caramel I gave you write access so you should now be able to push new branches to the repository. Typically in an open source project, you would fork the repository into your own personal github where you have full write access. You could then send the pull request from the forked repository.

**Comment by brandonschabell** [comment]
Pull request approved. Closing this issue.
